### ISSUE TITLE
ms in timestamp

### ISSUE THREAD

**Issue by klimashkin** [gulpjs/fancy-log#12]
I think `gulp-util` had `[HH:mm:ss:ms]` format, that was pretty useful sometimes.
Would be great to have it in `fancy-log` as well, or make it configurable

**Comment by phated** [comment]
No it didn't... https://github.com/gulpjs/gulp-util/blob/master/lib/log.js

**Comment by ceremcem** [comment]
@phated So, why Gulp is displaying milliseconds and fancy-log is not?

**Comment by yocontra** [comment]
@klimashkin I went way back to the original implementation when I first released gulp and it was `HH:MM:ss` https://github.com/gulpjs/gulp-util/commit/a4f941ec92eb7fd3224cd95b9f2dab617cfa1b20#diff-bfaf7f17089346f4cf68d867a9bed34fR5
