### ISSUE TITLE
Any ENV variable for support color output on CI environment without TTY

### ISSUE THREAD

**Issue by delagen** [gulpjs/fancy-log#13]
Used Gitlab CI and output does not get any ASCI color.
As I see dependency for detect TERM color support it return none for environments without TTY

**Comment by phated** [comment]
We already support you adding the `--color` flag to your command.

**Comment by delagen** [comment]
@phated you offer add parameter to EVERY gulp command issued in EVERY project?

**Comment by phated** [comment]
What are you talking about? The logger has nothing to do with your colors, just the color it adds to the timestamp.  Did you mean to open this on your **colors** dependency?

**Comment by phated** [comment]
We are working on a `--color`/`--no-color` feature of `gulp-cli` with the initial work done in https://github.com/gulpjs/gulp-cli/pull/137 but that's pretty far off and will require people to switch from fancy-log to the gulplog dependency.

**Comment by phated** [comment]
Or just use `chalk` like you used to through gulp-util.... I don't like recommending that module due to authorship but if you must, feel free.
