### ISSUE TITLE
Allow time-stamp patterns in fancy-log configuration instead of default HH:mm:ss

### ISSUE THREAD

**Issue by watery** [gulpjs/fancy-log#16]
Time-stamp accepts [several patterns](https://www.npmjs.com/package/time-stamp#usage) for the timestamp prefix, can fancy-log be made to receive them i.e. at module initialization?
It would be useful for multiday running applications.

**Comment by phated** [comment]
This is not a concern of fancy-log.  gulp-cli is going to get theming support but it's complicated and not done yet.

Ref https://github.com/gulpjs/gulp-cli/issues/63 and https://github.com/gulpjs/gulp-cli/pull/137
