### ISSUE TITLE
consider using time-stamp instead of dateformat?

### ISSUE THREAD

**Issue by jonschlinkert** [gulpjs/fancy-log#2]
dateformat has a relatively large dependency tree from the CLI that it ships with. I created [this issue](https://github.com/felixge/node-dateformat/issues/36) over there hoping to get it resolved since we use it quite a bit on other projects.

Would you consider a pr to use [time-stamp](https://github.com/jonschlinkert/time-stamp#usage) here instead? It only formats the time-stamp, so we'd still need chalk etc. Visually there should not be a difference in the output.

**Comment by phated** [comment]
:+1: mind sending a PR?

**Comment by jonschlinkert** [comment]
Sure, no problem!

**Comment by phated** [comment]
Closed by #3

**Comment by phated** [comment]
Published as 1.2.0 (wasn't sure if it felt like a minor or patch).
