### ISSUE TITLE
1.3.3 version: index.js use the console package,but package.json don't have console dependcy

### ISSUE THREAD

**Issue by lvdengmei** [gulpjs/fancy-log#20]
in the version 1.3.3 : index.js use the console package,but package.json don't have console dependcy

so if we want use this 1.3.3 we must add dependcy 
npm install --save console 

advice add this dependcy in the package.json

**Comment by phated** [comment]
Console is a package in node standard library, just like fs

**Comment by lvdengmei** [comment]
now we use the react-native @0.55.0 ,it depend on fbjs-scripts ^0.8.1, this use the fancy-log ,
when we build RN , failed . npm can't resolve the console, we have a try by the guide from https://github.com/facebook/react-native/issues/4968 ,but can't work .
with no way ,we just add the console package dependcy ,then it's ok 
 before it use the fancy-log 1.3.2 with no console , all is ok!
So i create this issue just want confirm every scense  will be ok

**Comment by phated** [comment]
ReactNative doesn't auto-bundle any node core modules within it's bundler.  This module doesn't support ReactNative.
