### ISSUE TITLE
Add support for showing Year, Month and Day

### ISSUE THREAD

**Issue by hildoer** [gulpjs/fancy-log#24]
Before you open this issue, please complete the following tasks:

### Describe your idea for a new feature

The current time only shows time. There is no date information. It would be nice to be able to show a date, or provide a format string to print the components of of the full time stamp exactly how I want to format it. 

### Explain the problem your idea is trying to solve

We are looking for a simply logging solution for some automation scripts that run somewhat sporadically based on need. We have a custom built solution right now and would rather use an off-the-shelf simple logger. But, we need full date time stamps or our logging is useless when we try to figure out "when was the last day this ran?". 

### How will it benefit gulp and its users?

Anyone who needs to know the day something logged. Or has some other custom timestamp parsing needs.

**Comment by camillo777** [comment]
Hello, what is the solution?
Is it documented somewhere?
