### ISSUE TITLE
Suppress Logs based on Flag [Suggestion]

### ISSUE THREAD

**Issue by boxman0617** [gulpjs/fancy-log#6]
I would really like to see a way to suppress the the output. Or even a way to filter some of the output.

**Comment by phated** [comment]
doesn't belong in fancy-log, the implementing CLI should handle the flag and not log, this is how gulp handles it

**Comment by boxman0617** [comment]
@phated What I meant was, there is instanced where you do not want the "sync:group 0" logs to be shown but others yes. It would be able to filter if both the timestamp and the message where going through console.log but they are not.
